
name: Gerar APK Flateon

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Preparar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Extrair projeto
        run: |
          mkdir -p projeto
          unzip -o FlateonAutoMove_Prototype.zip -d projeto

      - name: Preparar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.11.1'

      - name: Compilar APK
        run: |
          cd projeto/FlateonAutoMove
          gradle assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: FlateonAutoMove-APK
          path: projeto/FlateonAutoMove/app/build/outputs/apk/debug/app-debug.apk
